### ISSUE TITLE
onDidChange获取到的index有问题

### ISSUE THREAD

**Issue by liuyankai1990** [easyui/react-native-ezswiper#17]
onDidChange获取到的index有问题，从后往前返回时，获取不到正确的index（当滚动到第一个时获取到的index依然是1）

**Comment by liuyankai1990** [comment]
![image](https://user-images.githubusercontent.com/10486294/52939279-b2418b00-339e-11e9-99c2-fd672ff54f16.png)
![image](https://user-images.githubusercontent.com/10486294/52939319-d1401d00-339e-11e9-8182-463ed8591a0d.png)
查询代码之后发现使用了ceil。ceil为向上取整，所以index永远都不可能为0，导致index无法获取到准确的值

**Comment by easyui** [comment]
thx
