### ISSUE TITLE
android上开发过程中

### ISSUE THREAD

**Issue by wolfjobs** [easyui/react-native-ezswiper#5]
android上开发过程中，ezswiper在滑动到断点（['0', '1' ,'2','3'],在0和3的切换时）的时候会闪一下，请问还有其他人遇到的吗？这问题解决了没？

**Comment by panmin** [comment]
运到同样的问题

**Comment by zhrhuoa** [comment]
+1

**Comment by easyui** [comment]
详细运行环境？有解决？

**Comment by wolfjobs** [comment]
Now,there was no problem happened under these scene ：release & not debug remote ，so I close this issue，
